<script lang="ts">
	import { goto } from '$app/navigation';
	import { onMount } from 'svelte';

	import welcome from '$lib/images/svelte-welcome.webp';
	import welcomeFallback from '$lib/images/svelte-welcome.png';

	let joining = false;
	let error = '';
	let showInvite = false;
	let inviteCode = '';

	onMount(() => {
		try {
			const params = new URLSearchParams(window.location.search);
			const code = params.get('invite');
			if (code) {
				showInvite = true;
				inviteCode = code;
			}
		} catch (e) {
			// ignore when running server-side or malformed URL
		}
	});

	async function testJoin() {
		joining = true;
		error = '';
		try {
			const response = await fetch('/api/test-join', { method: 'POST' });
			const data = await response.json();
			if (data.success) {
				goto('/group');
			} else {
				error = data.error || 'Failed to join';
			}
		} catch (e: any) {
			error = e.message || 'Something went wrong';
		} finally {
			joining = false;
		}
	}
</script>
<section>

	<div style="text-align:center; margin:1rem 0">
		<button on:click={() => (showInvite = !showInvite)} style="margin-bottom:0.5rem">Join by invite code</button>
		{#if showInvite}
			<div>
				<input placeholder="Invite code" bind:value={inviteCode} style="padding:0.5rem; margin-right:0.5rem" />
				<button on:click={() => { if (inviteCode.trim()) window.location.href = `/api/groups/goto/${inviteCode.trim()}` }}>Go</button>
			</div>
		{/if}
	</div>

	<p>
		<span style=

"		position: absolute;
		height: 409px;
		left: 122px;
		right: 69px;
		top: 268px;
		
		font-family: 'Lora';
		font-style: italic;
		font-weight: 400;
		font-size: 24px;
		line-height: 61px;
		text-align: center;
		
		color: #000000;"
		
		> Soapbox is a web application that allows friends to get to know eachother better! Friends can join through invite links, and, by a specified time, a friend must submit a blog about something that interests them. Then, their friends must take a quiz on their friend's blog generated by Google Gemini. Then, they may make comments on the blog. The blogger rotates, allowing each friend to share something about themself.</span>



	</p>
	<footer style="text-align: center;">

		<a href="/settings" aria-label="create group" style="padding: 15px; text-align: center; width: 200px; position: fixed; bottom: 0; left: 50%; transform: translateX(-50%);">
			<button style="font-size: 18px; border-radius: 40px; background-color: #90D5FF; color: white; font-family: Monomaniac One; max-width: 20rem;">Create Group</button>
		</a>
	</footer>


</section>

